#!/usr/bin/env bash

result=$(docker run repo_client:latest 'rpm -qa' | grep 'httpd-2.4.6-93.el7.centos.x86_64')

echo "********************************************************"
if [ $result ]
then
	echo "+++++++++++++++++Success"
else
	echo "--------------------Fail"
fi
echo "********************************************************"

