#!/usr/bin/env bash

mkdir -p server/packages/

docker run -v $PWD/server/packages:/root/packages centos:centos7 bash -c \
	"mkdir -p /root/packages && \
	 yum update -y && \
	 yum install createrepo -y && \
	 cd /root/packages && \
	 repotrack httpd && \
	 createrepo ."
