#!/usr/bin/env bash

# stop the container
docker stop repo_test

# remove the container
docker rm repo_test

# build the image
docker build . -t apache_yum_repo

# run a container of the newly created image 
docker run \
	-it -d \
	--name yum_server \
	-p 8888:80 \
	--volume=$PWD/packages:/my_repo/packages \
	apache_yum_repo:latest
